In [22]:
!pip3 install arviz
import arviz as az

!pip3 install numpyro
import numpyro
import numpyro.distributions as dist
import jax
import jax.numpy as jnp
from jax import grad, jit, vmap, pmap, jacfwd, jacrev
from jax.random import PRNGKey as PK

import numpy as np
import time

import matplotlib.pyplot as plt
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
def f(x):
    return abs(x**3)

f(-3)

27

In [ ]:
df = grad(f)
df(-3.0)

DeviceArray(-27., dtype=float32, weak_type=True)

In [ ]:
def mapping(v):
  x = v[0]
  y = v[1]
  z = v[2]
  return jnp.array([x*x, y*z])

ff = jacfwd(mapping)
fr = jacrev(mapping)
v = jnp.array([4., 5., 6.])

In [ ]:
ff(v)

DeviceArray([[8., 0., 0.],
             [0., 6., 5.]], dtype=float32)

In [ ]:
fr(v)

DeviceArray([[8., 0., 0.],
             [0., 6., 5.]], dtype=float32)

In [ ]:
key = random.PRNGKey(0)
x = random.normal(key, (10,1))
print(x)
print(x.shape)

[[-0.3721109 ]
 [ 0.26423115]
 [-0.18252768]
 [-0.7368197 ]
 [-0.44030377]
 [-0.1521442 ]
 [-0.67135346]
 [-0.5908641 ]
 [ 0.73168886]
 [ 0.5673026 ]]
(10, 1)


In [ ]:
x.shape

(10,)

In [ ]:
@jit
def selu(x, alpha=1.67, lmbda=1.05):
  return lmbda * jnp.where(x > 0, x, alpha * jnp.exp(x) - alpha)

x = random.normal(key, (1000000,))
%timeit selu(x).block_until_ready()

1.3 ms ± 33.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
selu(x)

DeviceArray([ 2.093448  ,  0.21820937, -0.5104704 , ...,  0.03640566,
              0.7458341 ,  0.20638663], dtype=float32)

In [3]:
?numpyro.sample

In [4]:
?numpyro.plate

In [15]:
A=numpyro.sample('test', dist.Normal(0, 1), random.PRNGKey(1), sample_shape=(10, 10))

In [26]:
A = dist.Normal(0, 1).sample(PK(2), (1, 19))

In [27]:
A.shape

(1, 19)

In [29]:
A

DeviceArray(-0.32241175, dtype=float32)